main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('profile/', views.profile, name='profile'),
    path('hobby/', views.hobby, name='hobby'),
    path('project/', views.project, name='project'),
    path('experience/', views.experience, name='experience'),

    path('matakuliah/', views.form, name='form'),
    path('form/matakuliah', views.form, name='form')
]

project_name/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('biodata', include('story1.urls')),
]

story1/urls.py
from django.urls import path

from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.biodata, name='biodata'),
]

main/models.py
from django.db import models

# Create your models here.
class MataKuliah(models.Model):
	nama 		= models.CharField(max_length=100)
	dosen 		= models.CharField(max_length=100)
	sks 		= models.CharField(max_length=100)
	deskripsi 	= models.CharField(max_length=100)
	tahun 		= models.CharField(max_length=100)
	kelas 		= models.CharField(max_length=100)

story1/models.py
from django.db import models

# Create your models here.

main/forms.py
from django import forms
from .models import MataKuliah
from django.forms import ModelForm

class Input_Form(forms.ModelForm):
	class Meta:
		model = MataKuliah
		fields = [
		'nama', 
		'dosen', 
		'sks', 
		'deskripsi', 
		'tahun', 
		'kelas'
		]
	error_messages = {
		'required' : 'Please Type'
	}

	nama = forms.CharField(label='', required=False, max_length=100)

	dosen = forms.CharField(label='', required=False, max_length=100)

	sks = forms.CharField(label='', required=False, max_length=100)

	deskripsi = forms.CharField(label='', required=False, max_length=100)

	tahun = forms.CharField(label='', required=False, max_length=100)

	kelas = forms.CharField(label='', required=False, max_length=100)

main/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Input_Form


def home(request):
    return render(request, 'main/home.html')

def profile(request):
	return render(request, 'main/profile.html')

def project(request):
	return render(request, 'main/project.html')

def hobby(request):
	return render(request, 'main/hobby.html')

def experience(request):
	return render(request, 'main/experience.html')

def form(request):
	context={
		'input_form' : Input_Form,
	}
	return render (request, 'main/forms.html', context)

def matkul(request):
	'''
	return render(request, 'main/forms.html')
	'''
	form = Input_Form(request.POST or None)
	if (form.is_valid and request.method == "POST"):
		form.save()
	return render(request, 'forms.html', {'form': form})

story1/views.py
from django.shortcuts import render

def biodata(request):
    return render(request,"home.html")

main/templates/main/experience.html
{% extends 'base.html' %} 
{% load static %}

{% block meta %}
<title>Lilis Safitri</title>
{% endblock meta %}

{% block content %}
<body style = "background-color:#F3AD78">
    <!--Organization Experience-->
    <div class="container" id="experience">
        <div class="row">
            <div class="col text-center">
                <div class="organisasi" style="margin-top: 50px"><h1>Organization Experience</h1></div>
            </div>
        </div>

        <div class="row">
            <div class="col-md">
                <div class="card">
                    <img class="card-img-top" src="{% static 'img/osis.jpg' %}" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">OSIS SMP</h5>
                    </div>
                </div>
            </div>

            <div class="col-md">
                <div class="card">
                    <img class="card-img-top" src="{% static 'img/pramuka.jpg' %}" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">PRAMUKA</h5>
                    </div>
                </div>
            </div>

            <div class="col-md">
                <div class="card">
                    <img class="card-img-top" src="{% static 'img/paskibra.jpg' %}" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">PASKIBRA</h5>
                    </div>
                </div>
            </div>

            <div class="col-md">
                <div class="card">
                    <img class="card-img-top" src="{% static 'img/fuki.jpg' %}" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">FUKI </h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
{% endblock content %}

main/templates/main/forms.html
{% extends "base.html" %} 
{% load static %}

{% block meta %}
<title>Lilis Safitri</title>
{% endblock meta %}

{% block content %}
<h1 style = "color: black; margin-top: 50px"
class = "pb-3 mb-2 text-light text-center">
</h1>
<form action="matkul" method="POST">
	{% csrf_token %}
	<table>	
		<br>Nama Mata Kuliah: {{input_form.nama}}<br>
		<br>Dosen Pengajar: {{input_form.dosen}}<br>
		<br>Jumlah SKS: {{input_form.sks}}<br>
		<br>Tahun Ajaran: {{input_form.tahun}}<br>
		<br>Ruang Kelas: {{input_form.kelas}}<br>
		<br>Deskripsi: {{input_form.deskripsi}}<br>
		<input type="submit", value="Submit">
	</table>

</form>
{% endblock content %}

</html>

main/templates/main/hobby.html
{% extends 'base.html' %} 
{% load static %}

{% block meta %}
<title>Lilis Safitri</title>
{% endblock meta %}

{% block content %}
<body style = "background-color:#F3AD78">
<!--Hobby-->
        <div class="container" id="hobby">
            <div class="row">
                <div class="col text-center">
                    <h1 style="margin-top: 50px">Hobby</h1>
                </div>
            </div>

            <div class="row">
                <div class="col-md">
                    <div class="card">
                        <img class="card-img-top" src="{% static 'img/114196.jpg' %}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">Goblin</h5>
                        </div>
                    </div>
                </div>

                <div class="col-md">
                    <div class="card">
                        <img class="card-img-top" src="{% static 'img/114197.jpg' %}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">DOTS</h5>
                        </div>
                    </div>
                </div>

                <div class="col-md">
                    <div class="card">
                        <img class="card-img-top" src="{% static 'img/114198.jpg' %}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">Crash Landing On You</h5>
                        </div>
                    </div>
                </div>

                <div class="col-md">
                    <div class="card">
                        <img class="card-img-top" src="{% static 'img/114199.jpg' %}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">Hotel Del Luna</h5>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md">
                    <div class="card">
                        <img class="card-img-top" src="{% static 'img/114201.jpg' %}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">Pangandaran</h5>
                        </div>
                    </div>
                </div>

                <div class="col-md">
                    <div class="card">
                        <img class="card-img-top" src="{% static 'img/114200.jpg' %}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">Yogyakarta</h5>
                        </div>
                    </div>
                </div>
                
                <div class="col-md">
                    <div class="card">
                        <img class="card-img-top" src="{% static 'img/114202.jpg' %}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">Jakarta</h5>
                        </div>
                    </div>
                </div>

                <div class="col-md">
                    <div class="card">
                        <img class="card-img-top" src="{% static 'img/114203.jpg' %}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">Bandung</h5>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
{% endblock content %}
</html>

main/templates/main/home.html
{% extends 'base.html' %} 
{% load static %}

{% block meta %}
<title>Lilis Safitri</title>
{% endblock meta %}

{% block content %}
<body style = "background-color:#F3AD78"> 
    <!--Isi Website-->
    <div id="home">
        <div class="container">
            <div class="row">
                <div class="col-md">
                    <div class="judul" style="margin-top: 100px">
                        <h1 class="text-center" style="color: black;">Welcome to My World</h1>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6 d-flex justify-content-center">
                    <img src="{% static 'img/gambar.png' %}" alt="" class="thumbnail">
                </div>

                <div class="tulisan col-lg-6">
                    <p>Hai, perkenalkan namaku Lilis Safitri. Biasa dipanggil Cici atau Lilis. Aku berasal dari Bekasi, Jawa Barat.</p>
                    <p>Di dalam website ini sudah tersedia informasi tentang pengalaman, kegiatan yang sering dilakukan, karya, dan profil-ku.</p>
                    <p>Semoga kalian menyukainya.</p>
                </div>
            </div>    
        </div>
    </div>
</body>
{% endblock content %}

main/templates/main/profile.html
{% extends 'base.html' %} 
{% load static %}

{% block meta %}
<title>Lilis Safitri</title>
{% endblock meta %}

{% block content %}
<body style = "background-color:#FFD2B1"> 
    <!--Membuat profile-->
    <div class="jumbotron jumbotron-fluid" id="profile" style = "background-color:#FFD2B1">
        <div class="container">
            <div class="row">
                <div class="col-md">
                    <div class="cv" style="margin-bottom: 50px">
                        <h1 class="text-center" style="color: black;">Curriculum Vitae</h1>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <img class="text-center" src="{% static 'img/cici_lagi.jpg' %}" alt="" class="thumbnail">
                </div>

                <div class="col-md-6">
                    <p>
                        <table>
                            <tbody><tr><td><b>Data Pribadi</b></td></tr>
                                <tr><td><b>Nama Lengkap</b></td><td>:</td><td>Lilis Safitri</td></tr>
                                <tr><td><b>Nama Panggilan</b></td><td>:</td><td>Lilis, Cici</td></tr>
                                <tr><td><b>NPM</b></td><td>:</td><td>1906399272</td></tr>
                                <tr><td><b>Angkatan</b></td><td>:</td><td>Maung 2019</td></tr>
                                <tr><td><b>Jurusan</b></td><td>:</td><td>Sistem Informasi</td></tr>
                                <tr><td><b>Fakultas</b></td><td>:</td><td>Ilmu Komputer UI</td></tr>
                                <tr><td><b>Hobi</b></td><td>:</td><td>Menonton film / drama, Travelling</td></tr>
                            </tbody>
                        </table>
                    </p>
                </div>
            </div>    

            <div class="row">
                <div class="col-md-6">
                    <p>
                        <table>
                            <tbody><tr><td><b>Pendidikan</b></td></tr>
                                <tr><td>TK Islam Ar-Ridho</td><td>(2006-2007)</td></tr>
                                <tr><td>SDN Sabajaya 2</td><td>(2007-2013)</td></tr>
                                <tr><td>SMPN Terbuka 1 Cibarusah</td><td>(2013-2016)</td></tr>
                                <tr><td>SMA Islam Yaspia</td><td>(2016-2019)</td></tr>
                                <tr><td>Universitas Indonesia</td><td>(2019-Sekarang)</td></tr>
                            </tbody>
                        </table>
                    </p>
                </div>
                <div class="deskripsi col-md-6" style="font-size: x-large">
                    <p><b>Deskripsi</b></p><p>Saya adalah mahasiswa jurusan sistem informasi di Fasilkom UI. Saya tipe orang yang ceria dan suka bercerita, dan mudah beradaptasi. Saya sangat menyukai makanan pedas, salah satunya seblak. Saya juga sangat menyukai warna biru.</p>
                </div>
            </div>
        </div>
    </div>
</body>
{% endblock content %}

main/templates/main/project.html
{% extends 'base.html' %} 
{% load static %}

{% block meta %}
<title>Lilis Safitri</title>
{% endblock meta %}

{% block content %}
<body style = "background-color:#FFD2B1"> 
<!--Project-->
    <div class="jumbotron jumbotron-fluid" id="project" style = "background-color:#FFD2B1; margin-bottom:150px">
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="string"><h1>Project</h1></div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="">
                        <p class="h5">Maaf, belum tersedia :(</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
{% endblock content %}

story1/templates/home.html
{% extends 'base.html' %} 
{% load static %}
<!DOCTYPE html>
<head>

{% block meta %}
<title>Lilis Safitri</title>
{% endblock meta %}

{% block content %}   
    <body>
        <link rel="stylesheet" href="css/bootstrap.css" media="all" type="text/css">
        <center><h1 style="color: brown; margin-top: 70px">Curriculum Vitae</h1></center>
        <center><img src="{% static 'cici.jpg' %}" width="10%" height="10%"></center>
        <center><h1>Lilis Safitri</h1></center>
        <center><h3 style="color: brown;">lilis.safitri@ui.ac.id</h3></center>
        <center><table border="1" cellpadding= "10">
                    <td>NPM</td>
                    <td>1906399272</td>
                </tr>
                <tr>
                    <td>Angkatan</td>
                    <td>Maung 2019</td>
                </tr>
                <tr>
                    <td>Jurusan</td>
                    <td>Sistem Informasi</td>
                </tr>
                <tr>
                    <td>Fakultas</td>
                    <td>Fasilkom UI</td>
                </tr>
                <tr>
                    <td>Hobi</td>
                    <td>Membaca, menonton film</td>
                </tr>
            </table></center>
            <h2>Deskripsi</h2>
        <p>
            Saya adalah mahasiswa jurusan sistem informasi di Fasilkom UI. Saya tipe orang yang ceria dan suka bercerita, dan mudah beradaptasi.
        </p>
        <p>
            Saya sangat menyukai makanan pedas, salah satunya adalah seblak. Saya juga sangat menyukai warna biru.
        </p>
        <h2>Riwayat Pendidikan</h2>
        <ul>
                <li>TK Islam Ar-Ridho - Lulus 2007</li>
                <li>SDN Sabajaya 2 - Lulus 2013</li>
                <li>SMPN Terbuka 1 Cibarusah - Lulus 2016</li>
                <li>SMA Islam Yaspia - Lulus 2019</li>
                <li>Universitas Indonesia - Sekarang</li>
        </ul>
    <h2>Sosial Media</h2>
       <p> Instagram    <a href="https://www.instagram.com/lilisafitr"> @lilisafitr </a></p> 
    </body>
{% endblock content %}
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  	<meta charset="UTF-8">
  	<meta name="viewport" content="width=device-width, initial-scale=1.0">
  	<link rel="stylesheet" href="{% static 'css/style.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" media="all"?>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr"crossorigin="anonymous">
  {% block meta %}
  <title>Lilis Safitri</title>
  {% endblock meta %}
</head>

<body>
	<nav class="navbar fixed-top navbar-expand-lg navbar-light scrolling-navbar" style="background-color:#F3AD78">
    <div class="container">
        <a class="navbar-brand nav-link" href="{% url 'main:home' %}">Lilis Safitri</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav ml-auto">
            <a class="nav-item nav-link active" href="{% url 'main:home' %}">Home<span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link active" href="{% url 'main:profile' %}">Profile</a>
            <a class="nav-item nav-link active" href="{% url 'main:hobby' %}">Hobby</a>
            <a class="nav-item nav-link active" href="{% url 'main:project' %}">Project</a>
            <a class="nav-item nav-link active" href="{% url 'main:experience' %}">Experience</a>
            <a class="nav-item nav-link active" href="{% url 'main:form' %}">Form</a>
            <a class="nav-item nav-link active" href="{% url 'story1:biodata' %}">Biodata</a>
          </div>
        </div>
    </div>
  </nav>


  {% block content %}
  {% endblock content %}
  <!--footer-->
  <footer class="page-footer font-small" style="background-color:#bd5734">
    <div class="container">
      <div class="row">
        <div class="col foot">
          <h2 class="text-center">Follow me on social media!</h2>
        </div>
        <div class="col-sm-12">
          <ul class="list-inline social-buttons text-center mt-5">
            <li class="list-inline-item">
              <a href="https://line.me/ti/p/T9HIgVs4Im" target="_blank">
                <i class="fab fa-line"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="https://www.instagram.com/lilisafitr" target="_blank">
                <i class="fab fa-instagram"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="https://twitter.com/lilisafitr" target="_blank">
                <i class="fab fa-twitter"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="mailto:lilis.safitri@ui.ac.id" target="_blank">
                <i class="far fa-envelope"></i>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </footer>
  <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
  <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/script.js' %}"></script>
</body>
</html>